name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Run yarn install
        run: yarn install

      - name: Run yarn build
        run: yarn build

      - name: output dist directory contents
        run: ls -lah dist/

      - name: Push to S3
        run: aws s3 ls
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
